template: |
  {{- $app := .app }}
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: {{ $app.name }}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    project: default
    source:
      path: {{ $app.path }}
      repoURL: https://github.com/tuyentv96/argo-cd-example
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

apps: []
