apiVersion: v1
kind: Service # Create service
metadata:
  name: jaeger # Sets the service name
  labels:
    app: jaeger # Defines app to create service for
spec:
  type: LoadBalancer
  ports:
    - port: 6379 # Sets the port to run the postgres application
  selector:
    app: jaeger
  loadBalancerIP: 192.168.1.204
