apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  source:
    path: infra
    repoURL: https://github.com/tuyentv96/argo-cd-example
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
