apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-project
  namespace: argocd
spec:
  project: default
  source:
    path: application-set
    repoURL: https://github.com/tuyentv96/argo-cd-example
    targetRevision: HEAD
    helm:
      values: |
        apps:
        - name: echo-http
          path: raspberry/overlays/echo-http
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
