apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-project
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps
    repoURL: https://github.com/tuyentv96/argo-cd-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
