---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysecret2
spec:
  encryptedData:
    foo: AgBiPQgRhKyt0sZqisalayS3JlojoJ0VAmsKOdJoWWOcPGsG9O/dMT/Gbk00RXAXBRAditkzE/3Lcr+6T7usvPJYpAyHHlv8WinVtXiCYaRllZNdwgZYn3I00LH4lYLPmlLTmks6GtwTiWE7Po2duJ4wMpY7GEcXk0X66v/yDu40isbC/ZBK49Mo3qWFJKGPDKJf4OsDiq1mv6oFKLO3+N+eY+ivYek5sZCeigr2db3S4NIm9QfUI/2+av0Mv6V0W2wnOKTdiEyn/kd5CIXQeqefsMIcC0qGEyGear9yPsAMpT/0y2/fQKwPCP7DmHja5tS0RlJWxv2JhchowwnALtrd6bg1/6jyw0mu3FqBWlTWFED/sa2s5j7CiDECiXXDuTLO56MLnvKuYNTMoZS0ZrOWgth6F9croaIeWSWOZ8prNNNaYpreQnxLLy8H0TcEfIt0JAWXeg4KlA+ql89bU1kG8Q7OXVC+DWBkzGbycGa49/07kGl79w57Q3VAE8X3j6cgyotPGKczal5zZdDUnXoS62p1FFvyS3cx8SQdabauEc2uiR9IXxZAP/81RXFUuSolUrh77KNp+ZRXX9fuj+KVH0SuyamuOeKeAEHVMpTz6PVfn1v42iWYdWqKsuj2s5szsmtb6nmtILDFbdeWZzT6dKt/Uyj69XzoHeKx4Tm6AE81bDxKAgLj5LnfZChhZLbLIvs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysecret2
---
