apiVersion: v1
kind: Service
metadata:
  name: hello-app1-service
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: hello-app1
