---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysecret
spec:
  encryptedData:
    cf-api-token: AgBbTaxNuw/d8PCfiDMQr2uH+vloxrz6xJ+DtHAdu7Hr1uWRaCEUO5DnVPDYpISzsu9n5EDmrK3E18XSRWOb8Oe4eTxOSM/csmDv2jupnT9C/jnBoZq8MaA1r49rZXXP3z3J6cyl7lromcvcbYKD/bxt5wfcdoFk7D6X+4h/8d/pWJL0QxWCCW6vjdlEwXxmYErwdbz9RxvynbPUcuMmhHXfhvQ38PlYlOnzk6rtt+fgRbDI9bcatGRaYC3lCjicHbyxXBGtLkVlF3Ww0pgS3sA5VLtEDA2eL+9a+E0EeB3U7tjmq8ZwvtWDYxO+55dMGrt0l9lKNxcGp/phmzoOu9KlMcpIlM/VIXlNde2dvz7+dR8GsXad31BK2XEf8rl9NmBE8y5BrE+7/W5f4Ky72ECYWiMs/am4hChJvTcvNP40ebrIQ7nghcCKDNhM2zYIx2cKQJs0gOJWSOI6VyDpJ59+tFLLoa2pO/9dIOW1f9C4nGrExoZJdSQ/3G5Ig8jpVY/TWJAGUXGZdpmn9sHaHBmLfh1krRbbBpw+PJ0SUYVL9kVn9jiqym5mMAm32M+k3i81WZmBRI6cUAixQN7AdtC8TAgoWKQPoSo/RXKGWkBpWPEMpRow/VDG945xQQahSP54V83u6+K8+QllqDpRxtLp631HgMuuYIfCB58qt6GnbrHl+DCLxTdGvRkuf+iWh3VCXOyWKgvAkoQ+UaIi0hg6Wd2pu+TEm9wB9g4E4ug=
    foo: AgAVQnHEvqIrIyF9LDz0MnVEb/CeSZ2+uCjhN8x2hxFz+sKBCgBtMDUWf8Hqqs77XoulJ1o/EuyfFJ68hoOT4XZE3Y4+7c74xtBf5BDcMOb4mZi7uQ6fDBsb70uHzHiVAz0xa8FXSq36tO/JUinNQXkVfWVxpEHgpmAvteEGfjXV6M3D8bfwApKpgS4JrDphGxMYQz0QvFDzuyziqWK9KvD06IonOHm4gldeSy2RCxQlUI4ozOk4LEf5XI4/D7frsDO/YyUeYIG9QInVsXTnoIxdEQj09r4r+H6/U6LQyLRJ3N+fKGTBmrlxjqq83s1zPAg1C7LlcfGJZY/0fRvVHxDEvVTP/PaZTtPYrWonxllziuu1ZqM78UuzwRtg9j5Tt5b6uPPuL1U41oWcGnpjeJYMBePK314/8kQ854swUGAd39JVMXlA125rARG6LpNqcUBz2CMbpvnA8PXbCWvr5wdQT49EL1DBDWTHFc+yxoJgt/4mdH5amfWkRYkeSHdchgMM0fAffo0r0SPIVNSb9keSZ3+pgeSkl7QHJwI1/7SCdku3OpuQ4yiM5IrQ3k/M4QM94o8gEt6m0+/rSne32qYNd1N0j//qGbK58eYZj5GiBFfy0xF71HDTGEVURx2Ym20o21BH6nz46UPSB9nTt930zYB938CzdNRJhbGI+ShmUXT33aU2vSE6olidTEFk3VJSlZM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysecret
---
