apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base/hello-app1
configMapGenerator:
- name: app-env
  envs:
  - files/app.env
images:
- name: nginx
  newName: nginx
  newTag: "1.23.1"
