apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base/hello-app1

configMapGenerator:
- name: app-env
  behavior: merge
  envs:
  - files/app.env

patches:
- path: deployment.yaml

images:
- name: nginx
  newName: nginx
  newTag: "latest"
